version: 1

disable_existing_loggers: False

formatters:
  console_format:
    format: '%(asctime)s [%(levelname)s] - %(name)s: %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: console_format
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: console_format
    filename: logs/log.log

root:
  level: DEBUG
  handlers: [ console, file ]
